name: trigger-auto-release

on:
  schedule:
    - cron: "*/5 * * * *"
  # TODO: remove after testing
  push:
    branches:
      - 'main'

jobs:
  auto-release:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'gh-pages'

    - uses: actions/setup-node@v3
      with:
        node-version: "19"

    - uses: actions/cache@v3
      id: cache
      with:
        path: node_modules
        key: ${{ hashFiles('package-lock.json') }}
        restore-keys: npm

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install

    - name: Generate page data and publish it
      run: |
        node generate.js > docs/index.html
        git diff docs/index.html
        git config user.email "auto-release@example.com"
        git config user.name "AutoRelease"
        git add docs/index.html
        git commit -m "Auto-release"
        git push
